### ISSUE TITLE
Wine is working now

### ISSUE THREAD

**Issue by Bush-cat** [Marc-Pierre-Barbier/Genshin-Impact-on-linux#1]
Some people got it working with wine, it's very playable.
This Script works, just follow the steps:

https://www.playonlinux.com/en/app-4228.html

1. Install the game with the current playonlinux script.

2. Change the wine version to 5.19-staging. (Plain 5.19 didn't work for me)

3. Install dxvk

4. Start the game/launcher and let it download the game files.

5. Go to the downloaded game files at "~/PlayOnLinux\'s\ virtual\ drives/Genshin_Impact/drive_c/Program Files/Genshin Impact/Genshin Impact Game"  and execute the following script to patch the UnityPlayer.dll:

#! /bin/bash

dd if=<(echo -ne "\xc3") of=UnityPlayer.dll bs=1 seek=$((0x0148BDD0)) conv=notrunc
dd if=<(echo -ne "\xc3\xf5") of=UnityPlayer.dll bs=1 seek=$((0x0148C420)) conv=notrunc
dd if=<(echo -ne "\x31\xed") of=UnityPlayer.dll bs=1 seek=$((0x01B30933)) conv=notrunc

6. Run the game/launcher again, hit Launch, and it should work!

7. (Optional) Import the game location to lutris, set LutrisWine to the latest version (tested with 5.7.11), add the arguments: 
-nolog 2>/dev/null 1>/dev/null

**Comment by BushCcat** [comment]
7. (Optional, added by me) Import the game location to lutris, set LutrisWine to the latest version (tested with 5.7.11), add the arguments:
-nolog 2>/dev/null 1>/dev/null

**Comment by Marc-Pierre-Barbier** [comment]
the way to patch the game to run
the dll already changed between 1.0.0 and 1.1.0 so i don't think this is a good option on the long run
do the patch allow the anti cheat to run or does it just prevent it from starting?
because if the patch prevent the anti cheat from starting this will be patched to avoid cheater making this kind of patch risky since at any moment you are at risk of beeing detected as a cheater

**Comment by Marc-Pierre-Barbier** [comment]
here is a repo for the updated instructions
https://notabug.org/Krock/GI-on-Linux

**Comment by ghost** [comment]
we all know, but we want to not get banned and lose Venti/Ganyu

**Comment by ShayBox** [comment]
Delete the link and the the comments after it
