### ISSUE TITLE
Game crashes at launch [Ver. 1.3]

### ISSUE THREAD

**Issue by zyrotheisz** [Marc-Pierre-Barbier/Genshin-Impact-on-linux#6]
After the 1.3 update the game is no longer working for me. I wonder if someone is able to play? Sometimes I can see the mihoyo screen and then it closes. Sounds like they patched this method :/

**Comment by Marc-Pierre-Barbier** [comment]
i no longer have vmware and the game installed but you can try to
update vmware tools and give me any error logs

**Comment by smiley** [comment]
Same here, even after updating VMware Tools, fully reinstalling the game, and increasing VRAM to 4GB. It looks like 1.3 broke this.

**Comment by Marc-Pierre-Barbier** [comment]
damn any errors report ? or logs that i can at least look at ?

im going to reinstall the game to try

**Comment by smiley** [comment]
No, nothing. The general log just cuts off at "Initialized touch input" (with barely anything written), and there's no crash log or dump, even if I turn on WER local dumps.

**Comment by Marc-Pierre-Barbier** [comment]
ok i installed the game and tried some things and noticed somting strange : the game doesn't crash
yes it close itself but the return code is 0(no error) and the upload_crash.exe is never called

it looks more like they intentionaly blocked vms (even more than before) 
the remaining question is : am i wrong or right 

2nd observation : enablig the debugger attachment will open a windows wich close itself rapidly => it's intentional they are trying to keep us out

maybe the anti cheat ?

**Comment by smiley** [comment]
It was already not debuggable (can't even open handles to the process, Process Explorer can't), and you're right about it not crashing. I tried to track it with procmon but I saw nothing interesting in there. Also tried to change the graphics adapter's name to not include "VMware" but that didn't help.

For now I'm dual-booting to play Genshin, which works perfectly fine. (I can even use g-sync this time, heh) Bothersome sure but at least it works...

**Comment by zyrotheisz** [comment]
Sounds like it's the anti-cheat. I am using the game patched files for wine now. If they want so bad to avoid Linux/wine users and ban me, I am fine with it. I really dislike the idea of such an aggressive anti cheat measure for a game which is mostly single player anyways. I mean I understand not going for native support, but deliberately breaking compatibility (cough Epic Games) makes me lose empathy for the devs.

**Comment by Marc-Pierre-Barbier** [comment]
the game is broken im we will search for solution over there https://github.com/Marc-Pierre-Barbier/Genshin-Impact-on-linux/issues/7
